# Generated by Django 2.2.7 on 2019-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time_lim', models.IntegerField()),
                ('mem_lim', models.IntegerField()),
                ('description', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('example_inp', models.TextField()),
                ('exmaple_outp', models.TextField()),
                ('data_input', models.FileField(upload_to='')),
                ('data_output', models.FileField(upload_to='')),
            ],
        ),
    ]
