# Generated by Django 2.2 on 2019-12-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subm_id', models.IntegerField(default=0)),
                ('prob_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
                ('value', models.TextField()),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
