# Generated by Django 2.2 on 2019-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdfsdfds', models.TextField()),
            ],
        ),
    ]
