# Generated by Django 2.2.7 on 2019-12-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subm_id', models.IntegerField(default=0)),
                ('prob_id', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oj.MyUser')),
            ],
        ),
    ]
