# Generated by Django 2.2.7 on 2019-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
